### ISSUE TITLE
Can I use this in a n2DS XL?

### ISSUE THREAD

**Issue by sapsicle** [giltesa/Nintendo-3DS-USB-C-Kit#6]
Per title, I don't see either 2DS model listed as supported. Given I use my n2DS XL the most, I was hoping to mod that one, is there anything different internally that prevents the installation of the port?

**Comment by giltesa** [comment]
No, you cannot. For the 2DS, there is a specific version: https://github.com/giltesa/Nintendo-2DS-USB-C-Kit/

**Comment by sapsicle** [comment]
Must've missed that, thanks!
